# Generated by Django 5.1.2 on 2024-10-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prefixes", "0002_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="prefixes.prefix",
            ),
        ),
    ]
